{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-{{.Values.namespace}}-eks
  namespace: {{.Values.namespace}}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
      
  selector:
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end}}
{{- end }}
