apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Chart.Name }}-{{ .Values.namespace }}-spc
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  serviceAccountName: {{ .Values.serviceAccount.name }}
  parameters:
    objects: |
      - objectName: "{{ .Values.namespace }}/coto-redis/CONFIG"
        objectType: secretsmanager
        objectAlias: "REDIS_PASSWORD"
  secretObjects:
    - secretName: {{ .Chart.Name }}-{{ .Values.namespace }}-secret
      type: Opaque
      data:
        - objectName: "REDIS_PASSWORD"
          key: REDIS_PASSWORD
